package org.salva.task.court_reservation_system.controller;
import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.salva.task.court_reservation_system.dto.request.*; import org.salva.task.court_reservation_system.entity.*; import org.salva.task.court_reservation_system.enums.*; import org.salva.task.court_reservation_system.exception.*; import org.salva.task.court_reservation_system.repository.*; import org.salva.task.court_reservation_system.security.AccessControlService; import org.salva.task.court_reservation_system.security.CustomUserDetails; import org.springframework.http.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/tournaments") @RequiredArgsConstructor public class TournamentController {
 private final TournamentRepository tournamentRepository; private final TournamentParticipantRepository participantRepository; private final TournamentMatchRepository matchRepository; private final VenueRepository venueRepository; private final AccessControlService accessControl;
 @GetMapping public List<Tournament> list(){return tournamentRepository.findAll();}
 @PostMapping public ResponseEntity<Tournament> create(@Valid @RequestBody TournamentRequestDTO r,@AuthenticationPrincipal CustomUserDetails user){
  Long scope=accessControl.resolveVenueFilter(user);
  Long venueId=r.getVenueId();
  if(scope!=null){ if(venueId!=null)accessControl.requireSameVenueOrAdmin(venueId,user); venueId=scope; }
  Venue venue=venueId==null?null:venueRepository.findById(venueId).orElseThrow(()->new ResourceNotFoundException("Sede no encontrada"));
  return ResponseEntity.status(HttpStatus.CREATED).body(tournamentRepository.save(Tournament.builder().name(r.getName()).sportType(r.getSportType()).startDate(r.getStartDate()).maxParticipants(r.getMaxParticipants()).venue(venue).build())); }
 @PostMapping("/{id}/enroll") public ResponseEntity<Void> enroll(@PathVariable Long id,@AuthenticationPrincipal CustomUserDetails user){Tournament t=get(id);if(t.getStatus()!=TournamentStatus.INSCRIPCION)throw new BusinessException("La inscripción está cerrada");if(participantRepository.countByTournamentId(id)>=t.getMaxParticipants())throw new BusinessException("El torneo ya no tiene cupos");if(participantRepository.existsByTournamentIdAndUserId(id,user.getId()))throw new ValidationException("Ya está inscrito");participantRepository.save(TournamentParticipant.builder().tournament(t).user(user.getUser()).build());return ResponseEntity.status(HttpStatus.CREATED).build();}
 @PostMapping("/{id}/fixtures") public List<Map<String,Object>> generateFixtures(@PathVariable Long id,@AuthenticationPrincipal CustomUserDetails user){Tournament t=get(id);accessControl.requireSameVenueOrAdmin(venueIdOf(t),user);if(t.getStatus()!=TournamentStatus.INSCRIPCION)throw new BusinessException("Los fixtures ya fueron generados");List<TournamentParticipant> p=participantRepository.findByTournamentIdOrderByPointsDescWinsDesc(id);if(p.size()<2)throw new BusinessException("Se requieren al menos dos inscritos");List<TournamentMatch> matches=new ArrayList<>();for(int i=0;i<p.size();i++)for(int j=i+1;j<p.size();j++)matches.add(TournamentMatch.builder().tournament(t).playerOne(p.get(i).getUser()).playerTwo(p.get(j).getUser()).build());t.setStatus(TournamentStatus.EN_CURSO);tournamentRepository.save(t);return matchRepository.saveAll(matches).stream().map(this::matchDto).toList();}
 @GetMapping("/{id}/matches") public List<Map<String,Object>> matches(@PathVariable Long id){get(id);return matchRepository.findByTournamentId(id).stream().map(this::matchDto).toList();}
 @PatchMapping("/{id}/matches/{matchId}/result") public void result(@PathVariable Long id,@PathVariable Long matchId,@Valid @RequestBody MatchResultRequestDTO r,@AuthenticationPrincipal CustomUserDetails user){accessControl.requireSameVenueOrAdmin(venueIdOf(get(id)),user);TournamentMatch m=matchRepository.findById(matchId).orElseThrow(()->new ResourceNotFoundException("Partido no encontrado"));if(!m.getTournament().getId().equals(id))throw new ValidationException("El partido no pertenece al torneo");if(m.getCompleted())throw new BusinessException("El resultado ya fue registrado");if(r.getScoreOne().equals(r.getScoreTwo()))throw new ValidationException("Los empates no están habilitados");m.setScoreOne(r.getScoreOne());m.setScoreTwo(r.getScoreTwo());m.setCompleted(true);TournamentParticipant winner=participantRepository.findByTournamentIdAndUserId(id,r.getScoreOne()>r.getScoreTwo()?m.getPlayerOne().getId():m.getPlayerTwo().getId()).orElseThrow();TournamentParticipant loser=participantRepository.findByTournamentIdAndUserId(id,r.getScoreOne()>r.getScoreTwo()?m.getPlayerTwo().getId():m.getPlayerOne().getId()).orElseThrow();winner.setWins(winner.getWins()+1);winner.setPoints(winner.getPoints()+3);loser.setLosses(loser.getLosses()+1);participantRepository.save(winner);participantRepository.save(loser);matchRepository.save(m);}
 @GetMapping("/{id}/ranking") public List<Map<String,Object>> ranking(@PathVariable Long id){get(id);return participantRepository.findByTournamentIdOrderByPointsDescWinsDesc(id).stream().map(p->Map.<String,Object>of("userId",p.getUser().getId(),"name",p.getUser().getName(),"points",p.getPoints(),"wins",p.getWins(),"losses",p.getLosses())).toList();}
 private Long venueIdOf(Tournament t){return t.venueId();}
 private Tournament get(Long id){return tournamentRepository.findById(id).orElseThrow(()->new ResourceNotFoundException("Torneo no encontrado"));}
 private Map<String,Object> matchDto(TournamentMatch m){Map<String,Object> dto=new HashMap<>();dto.put("id",m.getId());dto.put("playerOneId",m.getPlayerOne().getId());dto.put("playerOne",m.getPlayerOne().getName());dto.put("playerTwoId",m.getPlayerTwo().getId());dto.put("playerTwo",m.getPlayerTwo().getName());dto.put("scoreOne",m.getScoreOne());dto.put("scoreTwo",m.getScoreTwo());dto.put("completed",m.getCompleted());return dto;}
}
